// SPDX-License-Identifier: Apache-2.0
/**
 * OSS control-plane catalog.
 *
 * A self-contained mirror of the platform's OSS-safe tool surface (the
 * `dojolm-web` Sensei registry). The MCP package ships standalone (`npx
 * @dojolm/mcp-control`), so it cannot import the app's source under its own
 * `rootDir` — instead the shapes are mirrored here and a TEST asserts parity
 * against the live registry (catalog.test.ts), catching drift.
 *
 * Coverage = FULL OSS-tier parity: every `SENSEI_TOOLS` entry whose route is
 * Apache (ships in OSS) and which has an external `/api/` endpoint is mirrored
 * here. The three BUSL-routed tools (`get_compliance`, `query_dna`,
 * `analyze_dna`) live in `catalog-ee.ts` (their routes vanish from the OSS
 * export, so OSS Sensei must never describe them — gap B). The `__client__` /
 * `__skill__` Sensei-internal sentinels are intentionally absent — they have no
 * external control-plane meaning. A coverage-parity test locks this set.
 *
 * The executor + the platform's `withAuth`/RBAC are the authoritative gate;
 * `minRole`/`scopeRequired` here are a friendlier pre-filter, not the security
 * boundary.
 */

import type { ControlToolDef } from '../types.js';

export const OSS_CATALOG: readonly ControlToolDef[] = [
  // --- read (viewer / read-scope) ---
  {
    name: 'list_models',
    title: 'List models',
    description: 'List configured LLM target models with provider and status.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: { type: 'string', description: 'Filter by provider name.' },
        enabled: { type: 'boolean', description: 'Filter by enabled status.' },
      },
    },
    endpoint: '/api/llm/models',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_stats',
    title: 'Get scanner stats',
    description: 'Scanner statistics: pattern, group, and source counts.',
    inputSchema: { type: 'object', properties: {} },
    endpoint: '/api/stats',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_guard_status',
    title: 'Get guard status',
    description: 'Hattori Guard status: enabled, mode, and block threshold.',
    inputSchema: { type: 'object', properties: {} },
    endpoint: '/api/llm/guard',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_results',
    title: 'Query test results',
    description: 'Query LLM test execution results with optional filters.',
    inputSchema: {
      type: 'object',
      properties: {
        modelId: { type: 'string', description: 'Filter by model id.' },
        status: { type: 'string', enum: ['completed', 'failed', 'running'], description: 'Filter by status.' },
        limit: { type: 'number', description: 'Max results (default 50).' },
      },
    },
    endpoint: '/api/llm/results',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'discover_local',
    title: 'Discover local models',
    description: 'Discover locally running models from Ollama, LMStudio, or LlamaCPP.',
    inputSchema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['ollama', 'lmstudio', 'llamacpp'], description: 'Local provider to query.' },
      },
      required: ['provider'],
    },
    endpoint: '/api/llm/providers/{provider}/discover',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_fingerprint_results',
    title: 'Get fingerprint results',
    description: 'Retrieve Kagami fingerprint probe results for a model.',
    inputSchema: {
      type: 'object',
      properties: {
        modelId: { type: 'string', description: 'Model id to get results for.' },
        mode: { type: 'string', enum: ['identify', 'verify'], description: 'Filter by fingerprint mode.' },
      },
    },
    endpoint: '/api/llm/fingerprint/results',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_leaderboard',
    title: 'Get resilience leaderboard',
    description: 'Models ranked by average security score, injection rate, and category breakdown.',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', description: 'Max models (1-100, default 20).' },
        category: { type: 'string', description: 'Filter by test category.' },
      },
    },
    endpoint: '/api/llm/leaderboard',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_guard_audit',
    title: 'Query guard audit',
    description: 'Hattori Guard audit events filtered by mode, direction, and action.',
    inputSchema: {
      type: 'object',
      properties: {
        mode: { type: 'string', enum: ['shinobi', 'samurai', 'sensei', 'hattori'] },
        direction: { type: 'string', enum: ['input', 'output'] },
        action: { type: 'string', enum: ['allow', 'block', 'log'] },
        limit: { type: 'number', description: 'Max results (1-100, default 25).' },
      },
    },
    endpoint: '/api/llm/guard/audit',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_ecosystem_findings',
    title: 'Query ecosystem findings',
    description: 'Cross-module findings (threats, vulnerabilities, variants) or aggregated stats.',
    inputSchema: {
      type: 'object',
      properties: {
        mode: { type: 'string', enum: ['query', 'stats'], description: 'Findings vs aggregated stats.' },
        sourceModule: { type: 'string', enum: ['scanner', 'atemi', 'sage', 'arena', 'mitsuke', 'attackdna', 'ronin', 'jutsu', 'guard'], description: 'Filter by source module.' },
        severity: { type: 'string', enum: ['CRITICAL', 'WARNING', 'INFO'] },
        search: { type: 'string', description: 'Text search across findings.' },
        limit: { type: 'number', description: 'Max results (default 50).' },
      },
    },
    endpoint: '/api/ecosystem/findings',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'list_campaigns',
    title: 'List campaigns',
    description: 'List Sengoku red-team campaigns with status and configuration.',
    inputSchema: { type: 'object', properties: {} },
    endpoint: '/api/sengoku/campaigns',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'list_arena_matches',
    title: 'List arena matches',
    description: 'List Kumite arena matches, optionally filtered by status.',
    inputSchema: {
      type: 'object',
      properties: {
        status: { type: 'string', enum: ['pending', 'running', 'completed', 'aborted'], description: 'Filter by match status.' },
        limit: { type: 'number', description: 'Max results (1-100, default 25).' },
      },
    },
    endpoint: '/api/arena',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'get_warriors',
    title: 'Get arena warriors',
    description: 'Arena warrior leaderboard: fighters ranked by win rate, scores, and match history.',
    inputSchema: { type: 'object', properties: {} },
    endpoint: '/api/arena/warriors',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'viewer',
    scopeRequired: 'read',
    tier: 'oss',
  },
  // --- scan / analysis (read-scope, non-mutating) ---
  {
    name: 'scan_text',
    title: 'Scan text',
    description: 'Scan text for prompt injection, jailbreak attempts, and other threats.',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Text to scan (max 10,000 chars).' },
        engines: { type: 'array', items: { type: 'string' }, description: 'Optional scanner engines.' },
      },
      required: ['text'],
    },
    endpoint: '/api/scan',
    method: 'POST',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'user',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'scan_format',
    title: 'Scan multi-format content',
    description: 'Scan a file or content with the Shingan multi-format scanner for hidden threats.',
    inputSchema: {
      type: 'object',
      properties: {
        content: { type: 'string', description: 'Content to scan.' },
        filename: { type: 'string', description: 'Optional filename hint for format detection.' },
      },
      required: ['content'],
    },
    endpoint: '/api/shingan/scan',
    method: 'POST',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'user',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'run_rag_pipeline_test',
    title: 'Scan RAG pipeline payloads',
    description: 'Scan adversarial RAG-style payloads (boundary injection, retrieval poisoning) with the scanner engine.',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'RAG poisoning payload to scan.' },
        engines: { type: 'array', items: { type: 'string' }, description: 'Optional scanner engines.' },
      },
      required: ['text'],
    },
    endpoint: '/api/scan',
    method: 'POST',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'user',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    // Non-mutating probe, but `requiresConfirmation: true` — fingerprinting an
    // external model actively probes it, so an explicit confirm is warranted.
    name: 'fingerprint',
    title: 'Fingerprint model',
    description: 'Run Kagami fingerprint probes to identify or verify an LLM model.',
    inputSchema: {
      type: 'object',
      properties: {
        modelId: { type: 'string', description: 'Model id to fingerprint.' },
        mode: { type: 'string', enum: ['identify', 'verify'], description: 'Identify an unknown model or verify a claimed identity.' },
        preset: { type: 'string', enum: ['quick', 'standard', 'full', 'verify', 'stealth'], description: 'Probe preset (default standard).' },
      },
      required: ['modelId', 'mode'],
    },
    endpoint: '/api/llm/fingerprint',
    method: 'POST',
    mutating: false,
    requiresConfirmation: true,
    minRole: 'user',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    // GET export, but confirmation-gated — produces a durable, distributable
    // report artifact.
    name: 'generate_report',
    title: 'Generate test report',
    description: 'Export test results as JSON, PDF, Markdown, CSV, or SARIF.',
    inputSchema: {
      type: 'object',
      properties: {
        batchId: { type: 'string', description: 'Batch id to export (omit for all recent results).' },
        format: { type: 'string', enum: ['json', 'pdf', 'markdown', 'csv', 'sarif'], description: 'Export format (default json).' },
      },
    },
    endpoint: '/api/llm/export',
    method: 'GET',
    mutating: false,
    requiresConfirmation: true,
    minRole: 'user',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'judge_response',
    title: 'Judge attack response',
    description: 'Judge whether an LLM response indicates a successful adversarial attack. Multi-criteria scoring.',
    inputSchema: {
      type: 'object',
      properties: {
        attackPayload: { type: 'string', description: 'The attack prompt that was sent.' },
        modelResponse: { type: 'string', description: 'The model response to evaluate.' },
        category: { type: 'string', description: 'Attack category for evaluation context.' },
      },
      required: ['attackPayload', 'modelResponse', 'category'],
    },
    endpoint: '/api/sensei/judge',
    method: 'POST',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'admin',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    name: 'predict_variants',
    title: 'Predict attack variants',
    description: 'Predict how an attack pattern will evolve using AttackDNA lineage and Sensei mutation intelligence.',
    inputSchema: {
      type: 'object',
      properties: {
        content: { type: 'string', description: 'The attack payload to analyze for variant prediction.' },
        category: { type: 'string', description: 'Attack category for mutation context.' },
      },
      required: ['content', 'category'],
    },
    endpoint: '/api/sensei/mutate',
    method: 'POST',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'admin',
    scopeRequired: 'read',
    tier: 'oss',
  },
  {
    // Non-mutating plan generation, confirmation-gated (it commissions a
    // multi-turn adversarial strategy).
    name: 'sensei_plan',
    title: 'Plan multi-turn attack',
    description: 'Generate a multi-turn adversarial attack conversation plan with step-by-step strategy.',
    inputSchema: {
      type: 'object',
      properties: {
        attackType: { type: 'string', description: 'Attack type (e.g. prompt-injection, jailbreak).' },
        targetDescription: { type: 'string', description: 'Description of the target system to attack.' },
        maxTurns: { type: 'number', description: 'Max conversation turns in the plan (1-50).' },
        context: { type: 'string', description: 'Optional additional target context.' },
      },
      required: ['attackType', 'targetDescription', 'maxTurns'],
    },
    endpoint: '/api/sensei/plan',
    method: 'POST',
    mutating: false,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'read',
    tier: 'oss',
  },
  // --- mutate (gated) ---
  {
    name: 'run_test',
    title: 'Run security test',
    description: 'Execute a single LLM security test case against a model.',
    inputSchema: {
      type: 'object',
      properties: {
        modelId: { type: 'string', description: 'Model id to test.' },
        testCaseId: { type: 'string', description: 'Test case id to run.' },
        useCache: { type: 'boolean', description: 'Use cached result if available (default true).' },
      },
      required: ['modelId', 'testCaseId'],
    },
    endpoint: '/api/llm/execute',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'user',
    scopeRequired: 'mutate',
    tier: 'oss',
  },
  {
    name: 'run_batch',
    title: 'Run test batch',
    description: 'Run a batch of LLM security tests across multiple models and test cases.',
    inputSchema: {
      type: 'object',
      properties: {
        modelIds: { type: 'array', items: { type: 'string' }, description: 'Model ids to test.' },
        testCaseIds: { type: 'array', items: { type: 'string' }, description: 'Test case ids to run.' },
      },
      required: ['modelIds', 'testCaseIds'],
    },
    endpoint: '/api/llm/batch',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'user',
    scopeRequired: 'mutate',
    tier: 'oss',
  },
  {
    name: 'create_arena_match',
    title: 'Create arena match',
    description: 'Launch a Kumite arena battle between two LLM models (CTF, KOTH, or RvB game modes).',
    inputSchema: {
      type: 'object',
      properties: {
        gameMode: { type: 'string', enum: ['CTF', 'KOTH', 'RvB'], description: 'Game mode: CTF, KOTH, or RvB.' },
        attackMode: { type: 'string', enum: ['kunai', 'shuriken', 'naginata', 'musashi'], description: 'Attack strategy.' },
        fighters: {
          type: 'array',
          items: { type: 'object', properties: { modelId: { type: 'string' }, modelName: { type: 'string' }, provider: { type: 'string' } }, required: ['modelId'] },
          description: 'Fighter objects (minimum 2; each needs modelId).',
        },
        maxRounds: { type: 'number', description: 'Max rounds (1-100).' },
        victoryPoints: { type: 'number', description: 'Victory point target (10-1000).' },
      },
      required: ['gameMode', 'attackMode', 'fighters'],
    },
    endpoint: '/api/arena',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'user',
    scopeRequired: 'mutate',
    tier: 'oss',
  },
  {
    name: 'create_campaign',
    title: 'Create campaign',
    description: 'Create a Sengoku red-team campaign targeting an LLM endpoint with selected attack skills.',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Campaign name (1-200 chars).' },
        targetUrl: { type: 'string', description: 'Target LLM endpoint URL.' },
        selectedSkillIds: { type: 'array', items: { type: 'string' }, description: 'Attack skill ids (1-100).' },
        targetSource: { type: 'string', enum: ['external', 'local', 'dashboard'], description: 'Target source (default external).' },
        targetModelId: { type: 'string', description: 'Model id when targetSource is "dashboard".' },
      },
      required: ['name', 'targetUrl', 'selectedSkillIds'],
    },
    endpoint: '/api/sengoku/campaigns',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'admin',
    tier: 'oss',
  },
  {
    name: 'run_campaign',
    title: 'Run campaign',
    description: 'Launch a Sengoku campaign run against its configured target. Long-running: returns a runId; poll get_campaign_run for status and findings.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'The campaign id to run.' },
      },
      required: ['id'],
    },
    endpoint: '/api/sengoku/campaigns/{id}/run',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'mutate',
    tier: 'oss',
    // Async launch: the route returns 202 + runId immediately and runs
    // fire-and-forget, so the launch must not block on the 30 s executor timeout.
    longRunning: { statusTool: 'get_campaign_run', pollAfterSeconds: 5 },
  },
  {
    name: 'get_campaign_run',
    title: 'Get campaign run',
    description: 'Get the status, progress, and findings summary of a Sengoku campaign run by id (poll this after run_campaign).',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'The campaign id.' },
        runId: { type: 'string', description: 'The run id returned by run_campaign.' },
      },
      required: ['id', 'runId'],
    },
    endpoint: '/api/sengoku/campaigns/{id}/runs/{runId}',
    method: 'GET',
    mutating: false,
    requiresConfirmation: false,
    minRole: 'admin',
    scopeRequired: 'read',
    tier: 'oss',
    // The run carries the full findings set — exempt from the 4 KB cap so an
    // external client receives it intact (redaction + HTML-strip still apply).
    noTruncate: true,
  },
  {
    name: 'set_guard_mode',
    title: 'Set guard mode',
    description: 'Change Hattori Guard mode (shinobi/samurai/sensei/hattori) or enable/disable it.',
    inputSchema: {
      type: 'object',
      properties: {
        enabled: { type: 'boolean', description: 'Enable or disable the guard.' },
        mode: { type: 'string', enum: ['shinobi', 'samurai', 'sensei', 'hattori'], description: 'Guard mode to set.' },
      },
      required: ['enabled', 'mode'],
    },
    endpoint: '/api/llm/guard',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'admin',
    tier: 'oss',
  },
  {
    name: 'generate_attack',
    title: 'Generate attack payloads',
    description: 'Generate adversarial attack payloads for a category. Returns novel variants for security testing.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', enum: ['prompt-injection', 'jailbreak', 'data-extraction', 'hallucination', 'toxicity', 'bias', 'pii-leak', 'system-prompt-leak'], description: 'Attack category.' },
        count: { type: 'number', description: 'Number of attack variants (1-100).' },
        severity: { type: 'string', enum: ['INFO', 'WARNING', 'CRITICAL'], description: 'Target severity.' },
        context: { type: 'string', description: 'Optional context about the target system.' },
      },
      required: ['category', 'count'],
    },
    endpoint: '/api/sensei/generate',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'admin',
    tier: 'oss',
  },
  {
    name: 'run_orchestrator',
    title: 'Run attack orchestrator',
    description: 'Run a multi-turn attack orchestrator (PAIR, Crescendo, TAP, MAD-MAX, or Sensei-Adaptive) against a target model.',
    inputSchema: {
      type: 'object',
      properties: {
        type: { type: 'string', enum: ['pair', 'crescendo', 'tap', 'mad-max', 'sensei-adaptive'], description: 'Orchestrator type.' },
        targetModelId: { type: 'string', description: 'Id of the target model to attack.' },
        attackerModelId: { type: 'string', description: 'Id of the attacking model.' },
        judgeModelId: { type: 'string', description: 'Id of the judge model.' },
        objective: { type: 'string', description: 'Attack objective.' },
        category: { type: 'string', description: 'Optional attack category for context.' },
        maxTurns: { type: 'number', description: 'Max conversation turns (1-100, default 20).' },
        maxBranches: { type: 'number', description: 'Max parallel branches (TAP/MAD-MAX only).' },
      },
      required: ['type', 'targetModelId', 'attackerModelId', 'judgeModelId', 'objective'],
    },
    endpoint: '/api/orchestrator/run',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'admin',
    tier: 'oss',
  },
  {
    // OSS, not EE: its route `/api/agentic` is Apache-2.0 (ships + functions in
    // the OSS build). Mirrored here so an OSS control-MCP describes it (gap B).
    name: 'run_agentic_test',
    title: 'Run agentic attack-surface test',
    description: 'Run agentic security tests against a tool-calling agent: indirect prompt injection across tool architectures.',
    inputSchema: {
      type: 'object',
      properties: {
        architecture: {
          type: 'string',
          enum: ['single-agent', 'multi-agent', 'hierarchical', 'debate', 'openai-functions', 'langchain-tools', 'code-interpreter', 'react-agent', 'mcp-tools', 'custom-schema'],
          description: 'Agent architecture / tool-wiring pattern to test.',
        },
        categories: { type: 'array', items: { type: 'string' }, description: 'Attack/tool categories to test.' },
        difficulty: { type: 'string', enum: ['easy', 'medium', 'hard', 'expert'], description: 'Difficulty level.' },
        objective: { type: 'string', description: 'Attack objective / test goal.' },
        targetModelId: { type: 'string', description: 'Id of the agent model to test.' },
      },
      required: ['architecture', 'categories', 'difficulty', 'objective', 'targetModelId'],
    },
    endpoint: '/api/agentic',
    method: 'POST',
    mutating: true,
    requiresConfirmation: true,
    minRole: 'admin',
    scopeRequired: 'admin',
    tier: 'oss',
  },
];
