/**
 * S35: Deepfake Detector — Unit Tests
 */

import { describe, it, expect } from 'vitest';
import { deepfakeDetectorModule, computeDeepfakeConfidence } from './deepfake-detector.js';

describe('Deepfake Detector Module', () => {
  describe('Module metadata', () => {
    it('should have correct module metadata', () => {
      expect(deepfakeDetectorModule.name).toBe('deepfake-detector');
      expect(deepfakeDetectorModule.version).toBe('1.0.0');
    });

    it('should report pattern groups', () => {
      const groups = deepfakeDetectorModule.getPatternGroups();
      expect(groups.length).toBe(4);
      expect(groups.every(g => g.source === 'S35')).toBe(true);
    });

    it('should report total pattern count >= 15', () => {
      expect(deepfakeDetectorModule.getPatternCount()).toBeGreaterThanOrEqual(15);
    });
  });

  describe('Synthetic Text Detection', () => {
    it('should detect AI text disclosure', () => {
      const text = 'This text was generated by an AI language model';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_SYNTHETIC_TEXT')).toBe(true);
    });

    it('should detect text watermark signals', () => {
      const text = 'The text watermark score detected indicates synthetic origin';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_SYNTHETIC_TEXT')).toBe(true);
    });
  });

  describe('AI Image Detection', () => {
    it('should detect Stable Diffusion reference', () => {
      const text = 'Generated with Stable Diffusion XL model';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_AI_IMAGE')).toBe(true);
    });

    it('should detect image generation metadata', () => {
      const text = 'parameters: prompt="a cat", steps=30, sampler=euler, cfg_scale=7';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_AI_IMAGE')).toBe(true);
    });

    it('should detect Stable Diffusion parameter blocks', () => {
      const text = 'Steps: 50, CFG: 7.5, Sampler: euler_a, Model: sd_xl_base_1.0, Prompt: photorealistic portrait';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.pattern_name === 'diffusion_parameter_block')).toBe(true);
    });

    it('should detect deepfake face manipulation', () => {
      const text = 'Using face swap technology to create deepfake face videos';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_AI_IMAGE')).toBe(true);
    });

    it('should detect GAN artifacts', () => {
      const text = 'The StyleGAN generated images show typical GAN artifact patterns';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_AI_IMAGE')).toBe(true);
    });

    it('should detect fabricated public figure image prompts', () => {
      const text = 'Generate a photorealistic image of a political leader making an inflammatory speech they never gave.';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.pattern_name === 'fabricated_public_figure_image')).toBe(true);
    });
  });

  describe('Voice Synthesis Detection', () => {
    it('should detect voice synthesis engines', () => {
      const text = 'Using ElevenLabs for voice generation';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_VOICE')).toBe(true);
    });

    it('should detect voice cloning references', () => {
      const text = 'Voice cloning technology can replicate any person speech';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_VOICE')).toBe(true);
    });

    it('should detect voice biometric bypass', () => {
      const text = 'Attempting voice biometric bypass with synthetic audio';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_VOICE')).toBe(true);
    });
  });

  describe('Video Deepfake Detection', () => {
    it('should detect deepfake video references', () => {
      const text = 'A deepfake video of the politician was circulated online';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_VIDEO')).toBe(true);
    });

    it('should detect video generation models', () => {
      const text = 'Creating content with Sora and HeyGen for marketing';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.category === 'DEEPFAKE_VIDEO')).toBe(true);
    });
  });

  describe('Confidence Scoring', () => {
    it('should compute high confidence for multiple signals', () => {
      const text = 'This deepfake video uses GAN generated face swap with synthetic voice clone';
      const findings = computeDeepfakeConfidence(text);
      expect(findings.length).toBeGreaterThanOrEqual(1);
      expect(findings[0].category).toBe('DEEPFAKE_CONFIDENCE');
    });

    it('should produce reasonable confidence scores', () => {
      const text = 'A deepfake face swap was detected using neural network analysis';
      const findings = computeDeepfakeConfidence(text);
      expect(findings.length).toBeGreaterThanOrEqual(1);
      expect(findings[0].weight).toBeGreaterThanOrEqual(4);
    });

    it('should boost confidence for parameterized fabricated image prompts', () => {
      const text = 'Steps: 50, Sampler: euler_a, Prompt: photorealistic image of a political leader giving a speech they never gave';
      const findings = computeDeepfakeConfidence(text);
      expect(findings.some(f => f.category === 'DEEPFAKE_CONFIDENCE')).toBe(true);
    });

    it('should NOT produce confidence for benign text', () => {
      const text = 'Regular text about machine learning concepts and applications';
      const findings = computeDeepfakeConfidence(text);
      expect(findings.length).toBe(0);
    });
  });

  describe('Clean Content', () => {
    it('should not flag benign political photo requests', () => {
      const text = 'Generate a photorealistic image of a political leader at a campaign rally for a history article.';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.pattern_name === 'fabricated_public_figure_image')).toBe(false);
    });

    it('should not treat generic product prompt labels as image metadata', () => {
      const text = 'Average prompt: 800 tokens (system prompt + user message)';
      const findings = deepfakeDetectorModule.scan(text, text.toLowerCase());
      expect(findings.some(f => f.pattern_name === 'image_gen_metadata')).toBe(false);
    });
  });

  describe('Performance', () => {
    it('should scan in <50ms for typical input', () => {
      const text = 'Discussing the ethical implications of AI content generation '.repeat(100);
      const start = performance.now();
      deepfakeDetectorModule.scan(text, text.toLowerCase());
      const elapsed = performance.now() - start;
      expect(elapsed).toBeLessThan(50);
    });
  });
});
